discord-token: # YOUR DISCORD TOKEN HERE
chat:
  channels:
#    - 0123456789
#    - 01248163264128256
  webhooks:
#    - https://discord.com/api/webhooks/...
  avatar:
#    Set to true on cracked servers,
#    for premium player heads to work:
    offline-mode: false

#    URL of player's avatar, which will be used on Discord
#
#    %player% is replaced by the player username
#    %uuid% is replaced by the player UUID,
#    if offline-mode is set to true, the plugin will use
#    the Mojang's API to get the correct UUID
#
#    Use this url to show faces instead of heads:
#    https://crafatar.com/avatars/%uuid%?overlay
    url: https://crafatar.com/renders/head/%uuid%?overlay
activity:
#  Interval (in seconds) of Discord activity updates
#  Activity is also updated every time a player enters or leaves the server
  update-interval: 60
