name: DiscordIntegration
version: 2.6.2
author: Dominik Korsa
main: com.dominikkorsa.discordintegration.DiscordIntegration
api-version: 1.16
softdepend:
  - PlaceholderAPI

permissions:
  discordintegration.command.reload:
    description: Allow users to use the /di reload command
    default: op
  discordintegration.command.link:
    description: Allow users to use the /di link command
    default: true
  discordintegration.command.unlink:
    description: Allow users to use the /di unlink command
    default: true
  discordintegration.notifyupdates:
    description: Users with this permission will get messages about Discord Integration updates when joining the server
    default: op
