name: DiscordIntegration
version: 1.9.0
author: Dominik Korsa
main: com.dominikkorsa.discordintegration.DiscordIntegration
api-version: 1.16

permissions:
  discordintegration.command.reload:
    description: Allow users to reload the configuration
