name: DiscordIntegration
version: 2.0.2
author: Dominik Korsa
main: com.dominikkorsa.discordintegration.DiscordIntegration
api-version: 1.17

permissions:
  discordintegration.command.reload:
    description: Allow users to reload the configuration
