name: DiscordIntegration
version: 2.4.1
author: Dominik Korsa
main: com.dominikkorsa.discordintegration.DiscordIntegration
api-version: 1.17

permissions:
  discordintegration.command.reload:
    description: Allow users to use the /di reload command
    default: op
  discordintegration.command.link:
    description: Allow users to use the /di link command
    default: true
